---
- name: 'Check if mongodb is installed'
  command: which mongod
  register: mongod_check
  ignore_errors: yes

- name: 'Install mongodb if not installed'
  include: 'mongodb.yaml'
  when: mongod_check != '/usr/bin/mongod'

- name: 'Start MongoDB'
  service:
    name: mongod
    state: started