---
- name: Install Nginx
  package:
    name: nginx
    state: latest
- name: Copy index.html
  copy:
    src: index.html
    dest: "/usr/share/nginx/html"
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Check connect
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    delay: 0
    timeout: 3
- name: Check url
  uri:
    url: http://localhost
    return_content: yes
  register: this
- debug:
    msg: "{{ this }}"